# Generated by Django 5.0.2 on 2024-05-26 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True)),
                ('capacity', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bus_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', help_text='Votre identité Sexuel', max_length=10)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BusManagement_App.bus')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', help_text='Votre identité Sexuel', max_length=10)),
                ('cnie', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('buses', models.ManyToManyField(to='BusManagement_App.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='BusManagement_App.route')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', help_text='Votre identité Sexuel', max_length=10)),
                ('grade', models.CharField(choices=[('PS4', 'Préscolaire 4 ans'), ('PS5', 'Préscolaire 5 ans'), ('CP', 'Cours préparatoire'), ('CE1', 'Cours élémentaire 1'), ('CE2', 'Cours élémentaire 2'), ('CM1', 'Cours moyen 1'), ('CM2', 'Cours moyen 2'), ('6E', 'Sixième'), ('5E', 'Cinquième'), ('4E', 'Quatrième'), ('3E', 'Troisième'), ('2ND', 'Seconde'), ('1RE', 'Première'), ('TLE', 'Terminale')], default='PS4', help_text="Niveau scolaire de l'élève", max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('distance_to_school', models.FloatField(default='0', help_text="Distance du domicile à l'école en kilomètres")),
                ('is_eligible_for_transport', models.BooleanField(default=False)),
                ('has_special_needs', models.BooleanField(default=False)),
                ('temporary_disability', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='BusManagement_App.parent')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryAddressRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_address_requests', to='BusManagement_App.student')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('is_passed', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='BusManagement_App.bus')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='BusManagement_App.student')),
            ],
        ),
        migrations.CreateModel(
            name='GeocodedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geocoded_addresses', to='BusManagement_App.student')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='BusManagement_App.route')),
            ],
        ),
        migrations.CreateModel(
            name='EtudiantItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateField()),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManagement_App.route')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManagement_App.student')),
            ],
            options={
                'unique_together': {('etudiant', 'itineraire')},
            },
        ),
    ]
