# Generated by Django 5.0.2 on 2024-05-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0002_initial'),
    ]

    operations = [
    ]
