# Generated by Django 5.0.2 on 2024-02-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0002_student_is_eligible_for_transport_safetycheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Inconnu', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='distance_to_school',
            field=models.FloatField(default=0, help_text="Distance du domicile à l'école en kilomètres"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='has_special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='temporary_disability',
            field=models.BooleanField(default=False),
        ),
    ]
