# Generated by Django 5.0.2 on 2024-02-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0003_student_address_student_distance_to_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='distance_to_school',
            field=models.FloatField(default=0, help_text="Distance du domicile à l'école en kilomètres"),
        ),
    ]
