# Generated by Django 5.0.2 on 2024-02-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0004_alter_student_distance_to_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='distance_to_school',
            field=models.FloatField(default=0, help_text="Distance du domicile à l'école en kilomètres"),
        ),
    ]
