# Generated by Django 5.0.2 on 2024-05-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0004_driver_sex_parent_sex_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetycheck',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_checks', to='BusManagement_App.student'),
        ),
    ]
