# Generated by Django 5.0.2 on 2024-05-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0005_safetycheck_etudiant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safetycheck',
            old_name='etudiant',
            new_name='student',
        ),
    ]
