# Generated by Django 5.0.2 on 2024-05-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0006_rename_etudiant_safetycheck_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bus_photos/'),
        ),
    ]
