# Generated by Django 5.0.2 on 2024-02-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0006_alter_student_distance_to_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('PS4', 'Préscolaire 4 ans'), ('PS5', 'Préscolaire 5 ans'), ('CP', 'Cours préparatoire'), ('CE1', 'Cours élémentaire 1'), ('CE2', 'Cours élémentaire 2'), ('CM1', 'Cours moyen 1'), ('CM2', 'Cours moyen 2'), ('6E', 'Sixième'), ('5E', 'Cinquième'), ('4E', 'Quatrième'), ('3E', 'Troisième'), ('2ND', 'Seconde'), ('1RE', 'Première'), ('TLE', 'Terminale')], default='PS4', help_text="Niveau scolaire de l'élève", max_length=10),
        ),
    ]
