# Generated by Django 5.0.2 on 2024-02-29 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0007_alter_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('CNIE', models.CharField(max_length=30)),
                ('Enfants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parents', to='BusManagement_App.student')),
            ],
        ),
    ]
