# Generated by Django 5.0.2 on 2024-03-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0009_parent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Email',
            field=models.CharField(default='Inconnu', max_length=30),
            preserve_default=False,
        ),
    ]
