# Generated by Django 5.0.2 on 2024-03-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0010_parent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='CNIE',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='Enfants',
        ),
        migrations.AddField(
            model_name='parent',
            name='enfant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='BusManagement_App.student'),
        ),
        migrations.AddField(
            model_name='parent',
            name='cnie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
