# Generated by Django 5.0.2 on 2024-03-02 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0011_remove_parent_cnie_remove_parent_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='enfant',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='BusManagement_App.parent'),
        ),
    ]
