# Generated by Django 5.0.2 on 2024-03-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0012_remove_parent_enfant_student_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_eligible_for_transport',
            field=models.BooleanField(default=True),
        ),
    ]
