# Generated by Django 5.0.2 on 2024-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0013_alter_student_is_eligible_for_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_eligible_for_transport',
            field=models.BooleanField(default=False),
        ),
    ]
