# Generated by Django 5.0.2 on 2024-03-17 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0014_alter_student_is_eligible_for_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantItineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManagement_App.student')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusManagement_App.route')),
            ],
            options={
                'unique_together': {('etudiant', 'itineraire')},
            },
        ),
    ]
