# Generated by Django 5.0.2 on 2024-04-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0015_etudiantitineraire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_point',
        ),
    ]
