# Generated by Django 5.0.2 on 2024-05-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0017_geocodedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocodedaddress',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geocoded_addresses', to='BusManagement_App.student'),
        ),
    ]
