# Generated by Django 5.0.2 on 2024-05-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0018_geocodedaddress_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryaddressrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='secondaryaddressrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondaryaddressrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
