# Generated by Django 5.0.2 on 2024-05-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0019_secondaryaddressrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryaddressrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='secondaryaddressrequest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='secondaryaddressrequest',
            name='longitude',
        ),
        migrations.AddField(
            model_name='secondaryaddressrequest',
            name='duration',
            field=models.IntegerField(choices=[(1, 'One Day'), (7, 'One Week'), (30, 'One Month')], null=True),
        ),
    ]
