# Generated by Django 5.0.2 on 2024-05-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0020_remove_secondaryaddressrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryaddressrequest',
            name='duration',
        ),
        migrations.AddField(
            model_name='secondaryaddressrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='secondaryaddressrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secondaryaddressrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
