# Generated by Django 5.0.2 on 2024-05-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0021_remove_secondaryaddressrequest_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryaddressrequest',
            name='duration',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
