# Generated by Django 5.0.2 on 2024-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusManagement_App', '0022_secondaryaddressrequest_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryaddressrequest',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
